testing: add a minimal deps travis test lane and add missing selectors that motivated the previous

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -12,10 +12,17 @@ matrix:
       python: 3.6
       env:
         - PYTHON_VER=3.6
+        - PROG=MINIMAL
     - os: linux
-      #python: 3.7
+      python: 3.6
+      env:
+        - PYTHON_VER=3.6
+        - PROG=FULL
+    - os: linux
+      python: 3.7
       env:
         - PYTHON_VER=3.7
+        - PROG=FULL
 
 before_install:
   - uname -a
@@ -29,7 +36,15 @@ before_install:
 
 install:
     # Create test environment for package
-  - python devtools/scripts/conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/base.yaml
+  - |
+    if [ $PROG == "MINIMAL" ]; then
+      python devtools/scripts/conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/minimal.yaml
+    elif [ $PROG == "FULL" ]; then
+      python devtools/scripts/conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/base.yaml
+    else
+      echo "ERROR: No match for PROG ($PROG)."
+      exit 1
+    fi
   - source activate test
 
     # Build and install package
